FROM php:7.1.2-cli

# Update first
RUN apt-get update

# For debugging
RUN apt-get install -y vim wget

# Include PHPUnit
RUN wget https://phar.phpunit.de/phpunit.phar \
	&& chmod +x phpunit.phar \
	&& mv phpunit.phar /usr/local/bin/phpunit \
	&& phpunit --version

# Include PostgreSQL extension
RUN apt-get install -y libghc-postgresql-libpq-dev \
	&& docker-php-ext-configure pgsql -with-pgsql=/usr/include/postgresql/ \ 
	&& docker-php-ext-install pgsql pdo_pgsql

# Allow us to collect logs
VOLUME  ["/var/log/apache2"]

# Now run the tests
# Development: for now, just run bash
CMD ["/bin/bash"]